ci: use app token for releases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,12 +63,52 @@ jobs:
     runs-on: ubuntu-latest
     needs: [test]
     steps:
+      - name: generate token
+        uses: actions/create-github-app-token@v1
+        id: generate-token
+        with:
+          app-id: ${{ secrets.APP_ID }} # <-- GitHub App ID secret name
+          private-key: ${{ secrets.APP_PRIVATE_KEY }} # <-- GitHub App private key secret name
       - name: setup rust
         uses: dtolnay/rust-toolchain@stable
       - name: checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ steps.generate-token.outputs.token }}
       - name: release
         uses: MarcoIeni/release-plz-action@v0.5
+        id: release-plz
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+      - name: Tag released PRs
+        env:
+          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
+          RELEASES: ${{ steps.release-plz.outputs.releases }}
+        run: |
+          set -e
+
+          # Iterate over released packages and add a label to the PRs
+          # shipped with the release.
+          for release in $(echo "$RELEASES" | jq -r -c '.[]'); do
+              package_name=$(echo "$release" | jq -r '.package_name')
+              version=$(echo "$release" | jq -r '.version')
+              prs_length=$(echo "$release" | jq '.prs | length')
+              if [ "$prs_length" -gt 0 ]; then
+                  # Create label.
+                  # Use `--force` to overwrite the label,
+                  # so that the command does not fail if the label already exists.
+                  label="released:$package_name-$version"
+                  echo "Creating label $label"
+                  gh label create $label --color BFD4F2 --force
+                  for pr in $(echo "$release" | jq -r -c '.prs[]'); do
+                      pr_number=$(echo "$pr" | jq -r '.number')
+                      echo "Adding label $label to PR #$pr_number"
+                      gh pr edit $pr_number --add-label $label
+                  done
+              else
+                  echo "No PRs found for package $package_name"
+              fi
+          done
+        shell: bash
